from __future__ import annotations

from lumen.knowledge.expansion_seed_data import EXPANSION_ENTRIES, EXPANSION_RELATIONSHIPS
from lumen.knowledge.models import KnowledgeEntry, KnowledgeFormula, KnowledgeRelationship


SEED_ENTRIES: tuple[KnowledgeEntry, ...] = (
    KnowledgeEntry(
        id="astronomy.space",
        title="Space",
        entry_type="concept",
        category="astronomy",
        subcategory="cosmology",
        aliases=("outer space", "space itself", "universe", "the universe", "cosmos", "the cosmos"),
        summary_short="Space is the vast physical expanse in which astronomical objects, radiation, fields, and matter exist.",
        summary_medium=(
            "Space is the vast physical expanse beyond and between astronomical objects. It is not perfectly empty: it contains radiation, particles, gas, dust, magnetic fields, gravity, stars, galaxies, and the large-scale structure of the universe."
        ),
        key_points=(
            "Outer space is much emptier than Earth's atmosphere, but it is not absolute nothingness.",
            "Astronomy studies objects and events in space, while cosmology studies the universe at the largest scales.",
            "Modern cosmology treats cosmic expansion as the stretching of space itself, not a normal explosion into pre-existing emptiness.",
        ),
        common_questions=("What is space?", "Is space empty?", "What is the universe?"),
        related_topics=("Cosmology", "Galaxy", "Milky Way", "Star", "Redshift"),
        tags=("astronomy", "cosmology", "universe", "space"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-04-21",
    ),
    KnowledgeEntry(
        id="astronomy.star",
        title="Star",
        entry_type="object",
        category="astronomy",
        subcategory="stellar_object",
        aliases=("stars", "regular star", "sun like star"),
        summary_short="A star is a massive luminous ball of hot plasma held together by gravity.",
        summary_medium=(
            "A star is a self-gravitating sphere of hot plasma that produces light and heat, usually by fusing lighter atomic nuclei in its core. "
            "Stars vary widely in mass, temperature, color, lifespan, and final fate."
        ),
        key_points=(
            "Stars shine because of energy released by nuclear fusion.",
            "They are the basic building blocks of galaxies.",
            "Some stars end as white dwarfs, neutron stars, or black holes depending on mass.",
        ),
        related_topics=("Black Hole", "Neutron Star", "Gravity"),
        tags=("astronomy", "stellar_object", "physics"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.93,
        last_updated="2026-03-24",
    ),
    KnowledgeEntry(
        id="astronomy.galaxy",
        title="Galaxy",
        entry_type="system",
        category="astronomy",
        subcategory="large_scale_structure",
        aliases=("galaxies",),
        summary_short="A galaxy is a huge gravitationally bound system of stars, gas, dust, and dark matter.",
        summary_medium=(
            "A galaxy is a vast gravitationally bound collection of stars, stellar remnants, gas, dust, and dark matter. "
            "Galaxies range from dwarfs to giant systems and can be spiral, elliptical, or irregular in shape."
        ),
        key_points=(
            "Galaxies contain enormous numbers of stars and interstellar matter.",
            "Gravity holds their visible matter and dark matter halos together.",
            "The Milky Way is the galaxy that contains the Solar System.",
        ),
        related_topics=("Milky Way", "Star", "Gravity"),
        tags=("astronomy", "galaxy", "structure"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.92,
        last_updated="2026-03-24",
    ),
    KnowledgeEntry(
        id="astronomy.milky_way",
        title="Milky Way",
        entry_type="system",
        category="astronomy",
        subcategory="galaxy",
        aliases=("the milky way", "milky way galaxy"),
        summary_short="The Milky Way is the spiral galaxy that contains the Solar System.",
        summary_medium=(
            "The Milky Way is the barred spiral galaxy that contains the Solar System. "
            "It holds hundreds of billions of stars along with gas, dust, star clusters, and a supermassive black hole at its center."
        ),
        key_points=(
            "The Sun is one ordinary star within the Milky Way.",
            "The Milky Way is a galaxy, not the whole universe.",
            "Its center hosts a supermassive black hole known as Sagittarius A*.",
        ),
        related_topics=("Galaxy", "Star", "Black Hole"),
        tags=("astronomy", "galaxy", "solar_system"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.93,
        last_updated="2026-03-24",
    ),
    KnowledgeEntry(
        id="astronomy.black_hole",
        title="Black Hole",
        entry_type="object",
        category="astronomy",
        subcategory="compact_object",
        aliases=("black holes",),
        summary_short="A black hole is a region of space where gravity is so strong that not even light can escape.",
        summary_medium=(
            "A black hole is a collapsed region of spacetime where gravity becomes so strong that the escape speed exceeds the speed of light. "
            "They often form after very massive stars collapse, and astronomers study them through their effects on nearby matter, light, and orbital motion."
        ),
        summary_deep=(
            "In general relativity, a black hole is defined by an event horizon: a boundary beyond which information cannot escape to an outside observer. "
            "Astrophysical black holes are inferred from accretion disks, high-energy emissions, gravitational lensing, and the motion of nearby stars or gas."
        ),
        key_points=(
            "A black hole has no solid surface in the ordinary sense.",
            "The event horizon marks the point of no return.",
            "Black holes are detected indirectly through their effects.",
        ),
        common_questions=("What is a black hole?", "How do black holes form?"),
        related_topics=("Neutron Star", "Gravity", "Saturn"),
        tags=("astronomy", "physics", "gravity", "relativity"),
        difficulty_level="general",
        examples=("Stellar-mass black holes form from massive star collapse.",),
        source_type="curated_local",
        confidence=0.92,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="astronomy.neutron_star",
        title="Neutron Star",
        entry_type="object",
        category="astronomy",
        subcategory="compact_object",
        aliases=("neutron stars",),
        summary_short="A neutron star is the ultra-dense collapsed core left behind after some massive stars explode.",
        summary_medium=(
            "A neutron star is a compact stellar remnant made mostly of neutrons. "
            "It packs more mass than the Sun into a city-sized object and still has a physical surface, unlike a black hole."
        ),
        key_points=(
            "Neutron stars are extremely dense.",
            "They can appear as pulsars when their radiation beams sweep past Earth.",
            "They differ from black holes because they still have a surface.",
        ),
        common_questions=("What is a neutron star?", "Black hole vs neutron star"),
        related_topics=("Black Hole", "Gravity"),
        tags=("astronomy", "stellar_remnant"),
        difficulty_level="general",
        examples=("Pulsars are rotating neutron stars with strong magnetic fields.",),
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="astronomy.saturn",
        title="Saturn",
        entry_type="object",
        category="astronomy",
        subcategory="planet",
        aliases=("planet saturn",),
        summary_short="Saturn is the sixth planet from the Sun and is best known for its bright ring system.",
        summary_medium=(
            "Saturn is a gas giant made mostly of hydrogen and helium. "
            "It is famous for its extensive rings, large moon system, and low average density compared with the other giant planets."
        ),
        key_points=(
            "Saturn is a gas giant.",
            "Its rings are made largely of ice and rock particles.",
            "It has many moons, including Titan.",
        ),
        common_questions=("Explain Saturn", "What is Saturn?"),
        related_topics=("Solar System",),
        tags=("astronomy", "planet", "gas_giant"),
        difficulty_level="general",
        examples=("Titan is Saturn's largest moon.",),
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="astronomy.mars",
        title="Mars",
        entry_type="object",
        category="astronomy",
        subcategory="planet",
        aliases=("planet mars", "the red planet", "red planet"),
        summary_short="Mars is the fourth planet from the Sun and is often called the Red Planet.",
        summary_medium=(
            "Mars is a rocky planet with a thin carbon-dioxide atmosphere, polar ice caps, volcanoes, canyons, and evidence that liquid water shaped parts of its ancient surface."
        ),
        key_points=(
            "Mars is smaller and colder than Earth.",
            "Iron-rich dust gives Mars its reddish color.",
            "Robotic missions study Mars to understand planetary history and whether it may once have supported habitable environments.",
        ),
        common_questions=("What is Mars?", "Tell me about Mars", "Why is Mars red?"),
        related_topics=("Solar System", "Earth", "Moon"),
        tags=("astronomy", "planet", "mars", "solar_system"),
        difficulty_level="general",
        examples=("Olympus Mons on Mars is one of the largest volcanoes in the Solar System.",),
        source_type="curated_local",
        confidence=0.91,
        last_updated="2026-04-24",
    ),
    KnowledgeEntry(
        id="astronomy.moon",
        title="Moon",
        entry_type="object",
        category="astronomy",
        subcategory="natural_satellite",
        aliases=("the moon", "earth's moon", "earth moon", "lunar", "luna"),
        summary_short="The Moon is Earth's natural satellite and the brightest object in the night sky after the Sun.",
        summary_medium=(
            "The Moon is Earth's only natural satellite. It affects tides, reflects sunlight through its phases, "
            "and preserves a heavily cratered surface that records Solar System history."
        ),
        key_points=(
            "The Moon orbits Earth about once every 27.3 days relative to the stars.",
            "Its gravity helps drive ocean tides on Earth.",
            "Its phases come from how sunlight falls on the Moon as seen from Earth.",
        ),
        common_questions=("What is the Moon?", "Tell me about the Moon", "Why does the Moon have phases?"),
        related_topics=("Earth", "Solar System", "Gravity"),
        tags=("astronomy", "moon", "lunar", "earth"),
        difficulty_level="general",
        examples=("A full Moon occurs when the Moon is opposite the Sun from Earth's point of view.",),
        source_type="curated_local",
        confidence=0.91,
        last_updated="2026-04-24",
    ),
    KnowledgeEntry(
        id="astronomy.solar_system",
        title="Solar System",
        entry_type="system",
        category="astronomy",
        subcategory="planetary_system",
        aliases=("the solar system",),
        summary_short="The Solar System is the Sun and all the objects gravitationally bound to it.",
        summary_medium=(
            "The Solar System includes the Sun, planets, dwarf planets, moons, asteroids, comets, and smaller bodies that orbit under the Sun's gravity."
        ),
        key_points=("The Sun dominates the system's mass.", "Planets orbit the Sun due to gravity."),
        related_topics=("Saturn", "Gravity"),
        tags=("astronomy", "system"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.88,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="astronomy.comet",
        title="Comet",
        entry_type="object",
        category="astronomy",
        subcategory="small_body",
        aliases=("comets", "a comet", "the comet"),
        summary_short="A comet is a small icy body that orbits the Sun and can grow a glowing coma and tail when it gets warm.",
        summary_medium=(
            "A comet is a small body made mostly of ice, dust, and rocky material that travels around the Sun. "
            "When a comet moves close enough to the Sun, heat turns some of its ice into gas, creating a fuzzy glow and often a long tail."
        ),
        key_points=(
            "Comets are leftovers from the early Solar System.",
            "Their tails point away from the Sun because sunlight and the solar wind push material outward.",
            "Most of the time a comet is just a cold, dark body until it comes closer to the Sun.",
        ),
        related_topics=("Solar System", "Orbit", "Milky Way"),
        tags=("astronomy", "small_body", "solar_system"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-24",
    ),
    KnowledgeEntry(
        id="astronomy.event_horizon",
        title="Event Horizon",
        entry_type="concept",
        category="astronomy",
        subcategory="relativity",
        aliases=("black hole event horizon",),
        summary_short="An event horizon is the boundary around a black hole beyond which escape is no longer possible.",
        summary_medium=(
            "An event horizon is the boundary surrounding a black hole where the escape speed reaches the speed of light. "
            "From outside that boundary, anything crossing inward can no longer send information back out."
        ),
        key_points=(
            "It is a boundary, not a physical surface.",
            "The event horizon marks the point of no return.",
        ),
        related_topics=("Black Hole", "Gravity"),
        tags=("astronomy", "relativity", "black_hole"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="astronomy.orbit",
        title="Orbit",
        entry_type="process",
        category="astronomy",
        subcategory="celestial_mechanics",
        aliases=("orbital motion", "orbits"),
        summary_short="An orbit is the path one body follows around another under gravity.",
        summary_medium=(
            "An orbit is the repeating path a body follows around another body because gravity continuously bends its motion. "
            "Planets, moons, and satellites all move in orbits that depend on mass, speed, and distance."
        ),
        key_points=(
            "Orbits happen because forward motion and gravity balance continuously.",
            "Different orbital shapes include circles and ellipses.",
        ),
        related_topics=("Gravity", "Solar System", "Saturn"),
        tags=("astronomy", "physics", "motion"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.89,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="science.science",
        title="Science",
        entry_type="discipline",
        category="science",
        subcategory="method",
        aliases=("the sciences",),
        summary_short="Science is a systematic way of building knowledge through observation, testing, and revision.",
        summary_medium=(
            "Science is a method for understanding the natural world by forming explanations, testing them against evidence, and revising them when the evidence changes. "
            "Its strength comes from repeatability, critique, and the willingness to update conclusions."
        ),
        key_points=(
            "Science depends on evidence, not just assertion.",
            "Hypotheses and models are tested against observation.",
            "Scientific knowledge improves through correction and refinement.",
        ),
        related_topics=("History", "Gravity", "Energy"),
        tags=("science", "method", "evidence"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.91,
        last_updated="2026-03-24",
    ),
    KnowledgeEntry(
        id="physics.gravity",
        title="Gravity",
        entry_type="concept",
        category="physics",
        subcategory="fundamental_interaction",
        aliases=("gravitational force",),
        summary_short="Gravity is the interaction that causes masses to attract one another.",
        summary_medium=(
            "Gravity is the interaction that pulls matter together. "
            "In everyday physics it explains falling objects and orbits, while in general relativity it is described as the curvature of spacetime caused by mass and energy."
        ),
        key_points=("Gravity shapes planetary motion.", "Gravity is weak compared with other fundamental forces but dominates at large scales."),
        related_topics=("Black Hole", "Solar System"),
        tags=("physics", "force"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="physics.acceleration",
        title="Acceleration",
        entry_type="concept",
        category="physics",
        subcategory="mechanics",
        aliases=("accelerations",),
        summary_short="Acceleration describes how quickly velocity changes over time.",
        summary_medium=(
            "Acceleration measures how fast an object's velocity changes, including changes in speed, direction, or both. "
            "It is central to mechanics because forces produce acceleration."
        ),
        key_points=(
            "Acceleration can change direction as well as speed.",
            "Its standard unit is meters per second squared.",
        ),
        related_topics=("Newton's Second Law",),
        tags=("physics", "mechanics", "motion"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="physics.atom",
        title="Atom",
        entry_type="object",
        category="physics",
        subcategory="matter",
        aliases=("atoms",),
        summary_short="An atom is the basic unit of ordinary matter, made of a nucleus and surrounding electrons.",
        summary_medium=(
            "An atom is the smallest ordinary unit of an element that still keeps that element's chemical identity. "
            "It has a dense nucleus of protons and neutrons with electrons arranged around it."
        ),
        related_topics=("Energy", "Force"),
        tags=("physics", "matter", "chemistry"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-24",
    ),
    KnowledgeEntry(
        id="history.history",
        title="History",
        entry_type="discipline",
        category="history",
        subcategory="field",
        aliases=("the past",),
        summary_short="History is the study of the past through evidence, records, and interpretation.",
        summary_medium=(
            "History is the study of past people, events, institutions, and ideas through evidence, records, and interpretation. "
            "It asks what happened, why it happened, and how change unfolded over time."
        ),
        key_points=(
            "History uses evidence rather than memory alone.",
            "It studies change, continuity, conflict, and cause over time.",
            "Interpretation matters because sources are incomplete and context-dependent.",
        ),
        related_topics=("George Washington", "American Revolution", "American Civil War"),
        tags=("history", "evidence", "interpretation"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.94,
        last_updated="2026-03-24",
    ),
    KnowledgeEntry(
        id="history.george_washington",
        title="George Washington",
        entry_type="person",
        category="history",
        subcategory="political_figure",
        aliases=("washington", "president washington"),
        summary_short="George Washington was the first President of the United States and a central figure in the American Revolution.",
        summary_medium=(
            "George Washington led the Continental Army during the American Revolution and later became the first President of the United States. "
            "He helped establish many early norms of the presidency, including the peaceful transfer of power."
        ),
        key_points=(
            "Washington led the Continental Army.",
            "He served as the first U.S. president.",
            "He set early presidential precedents.",
        ),
        common_questions=("Who was George Washington?",),
        related_topics=("American Revolution",),
        tags=("history", "united_states", "president"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.93,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="history.american_revolution",
        title="American Revolution",
        entry_type="event",
        category="history",
        subcategory="revolution",
        aliases=("american revolutionary war",),
        summary_short="The American Revolution was the political and military struggle through which the American colonies gained independence from Britain.",
        summary_medium=(
            "The American Revolution was a late-18th-century conflict and political transformation in which thirteen British colonies in North America fought for and secured independence."
        ),
        related_topics=("George Washington",),
        tags=("history", "revolution"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.89,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="history.abraham_lincoln",
        title="Abraham Lincoln",
        entry_type="person",
        category="history",
        subcategory="political_figure",
        aliases=("lincoln", "president lincoln"),
        summary_short="Abraham Lincoln was the 16th President of the United States and led the country through the Civil War.",
        summary_medium=(
            "Abraham Lincoln served as U.S. president during the Civil War and is especially remembered for preserving the Union and advancing the abolition of slavery. "
            "His presidency reshaped the role of the federal government and the moral direction of the war."
        ),
        key_points=(
            "Lincoln led the United States during the Civil War.",
            "He issued the Emancipation Proclamation.",
            "He is closely tied to the abolition of slavery in the United States.",
        ),
        related_topics=("American Civil War",),
        tags=("history", "united_states", "president"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.92,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="history.american_civil_war",
        title="American Civil War",
        entry_type="event",
        category="history",
        subcategory="war",
        aliases=("civil war", "u.s. civil war", "u s civil war", "you s civil war"),
        summary_short="The American Civil War was a mid-19th-century conflict between the Union and the Confederacy.",
        summary_medium=(
            "The American Civil War was fought from 1861 to 1865 over secession, slavery, and the future of the United States. "
            "It ended with Union victory and major constitutional changes, including the abolition of slavery."
        ),
        key_points=(
            "It was fought between the Union and the Confederacy.",
            "The war ended slavery in the United States.",
        ),
        related_topics=("Abraham Lincoln",),
        tags=("history", "war", "united_states"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="math.quadratic_formula",
        title="Quadratic Formula",
        entry_type="formula",
        category="math",
        subcategory="algebra",
        aliases=("the quadratic formula",),
        summary_short="The quadratic formula gives the solutions of a quadratic equation.",
        summary_medium=(
            "The quadratic formula is used to solve equations of the form ax^2 + bx + c = 0 by expressing the roots directly in terms of a, b, and c."
        ),
        key_points=(
            "It solves any quadratic equation with a nonzero a.",
            "The discriminant b^2 - 4ac determines the nature of the roots.",
        ),
        common_questions=("What is the quadratic formula?",),
        related_topics=("Derivative",),
        tags=("math", "algebra", "formula"),
        difficulty_level="general",
        examples=("For x^2 - 5x + 6 = 0, the roots are 2 and 3.",),
        source_type="curated_local",
        confidence=0.95,
        last_updated="2026-03-22",
        formula=KnowledgeFormula(
            formula_text="x = (-b ± sqrt(b^2 - 4ac)) / (2a)",
            variable_meanings={
                "a": "coefficient of x^2",
                "b": "coefficient of x",
                "c": "constant term",
                "x": "solution of the equation",
            },
            units={},
            interpretation="It returns the roots of a quadratic equation ax^2 + bx + c = 0.",
            example_usage="For x^2 - 5x + 6 = 0, a=1, b=-5, c=6, so the solutions are x=2 and x=3.",
        ),
    ),
    KnowledgeEntry(
        id="math.derivative",
        title="Derivative",
        entry_type="concept",
        category="math",
        subcategory="calculus",
        aliases=("derivatives",),
        summary_short="A derivative measures how a quantity changes with respect to another quantity.",
        summary_medium="In calculus, a derivative describes the instantaneous rate of change of a function and is closely related to the slope of a tangent line.",
        tags=("math", "calculus"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="math.integral",
        title="Integral",
        entry_type="concept",
        category="math",
        subcategory="calculus",
        aliases=("integrals",),
        summary_short="An integral is a mathematical way to accumulate quantities across an interval.",
        summary_medium=(
            "In calculus, an integral represents accumulation, total change, or area under a curve depending on context. "
            "It is closely linked to derivatives through the fundamental theorem of calculus."
        ),
        key_points=(
            "Integrals can represent total accumulated quantity.",
            "Definite integrals are often interpreted as signed area under a curve.",
        ),
        related_topics=("Derivative",),
        tags=("math", "calculus"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="math.pythagorean_theorem",
        title="Pythagorean Theorem",
        entry_type="formula",
        category="math",
        subcategory="geometry",
        aliases=(
            "pythagorean theorem formula",
            "a squared plus b squared equals c squared",
            "squared plus b squared equals c squared",
            "a square plus b square equals c square",
        ),
        summary_short="The Pythagorean theorem relates the sides of a right triangle.",
        summary_medium="The Pythagorean theorem states that in a right triangle, the square of the hypotenuse equals the sum of the squares of the other two sides.",
        key_points=(
            "It applies specifically to right triangles.",
            "It is commonly written as a^2 + b^2 = c^2.",
        ),
        related_topics=("Quadratic Formula",),
        tags=("math", "geometry", "formula"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.94,
        last_updated="2026-03-22",
        formula=KnowledgeFormula(
            formula_text="a^2 + b^2 = c^2",
            variable_meanings={"a": "one leg of the triangle", "b": "the other leg", "c": "the hypotenuse"},
            units={},
            interpretation="For a right triangle, the longest side is determined by the other two sides.",
            example_usage="If a = 3 and b = 4, then c = 5.",
        ),
    ),
    KnowledgeEntry(
        id="physics.voltage",
        title="Voltage",
        entry_type="concept",
        category="physics",
        subcategory="electricity",
        aliases=("electric potential difference",),
        summary_short="Voltage is the electric potential difference between two points.",
        summary_medium=(
            "Voltage describes how much electric potential energy per unit charge differs between two points. "
            "In circuits, it is the push that drives charge through components when a complete path exists."
        ),
        key_points=("Voltage is measured in volts.", "Voltage is not the same thing as current."),
        common_questions=("What is voltage?",),
        related_topics=("Current", "Resistance", "Ohm's Law"),
        tags=("physics", "electricity", "engineering"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.92,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="physics.current",
        title="Current",
        entry_type="concept",
        category="physics",
        subcategory="electricity",
        aliases=("electric current",),
        summary_short="Current is the rate at which electric charge flows.",
        summary_medium="Electric current measures how much charge passes a point per unit time in a circuit.",
        related_topics=("Voltage", "Resistance", "Ohm's Law"),
        tags=("physics", "electricity"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="physics.resistance",
        title="Resistance",
        entry_type="concept",
        category="physics",
        subcategory="electricity",
        aliases=("electrical resistance", "ohm", "ohms"),
        summary_short="Resistance measures how strongly a material or component opposes electric current.",
        summary_medium="Resistance describes how much a material or component opposes current flow and is measured in ohms.",
        related_topics=("Voltage", "Current", "Ohm's Law"),
        tags=("physics", "electricity"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="physics.power",
        title="Power",
        entry_type="concept",
        category="physics",
        subcategory="electricity",
        aliases=("electrical power", "watt", "watts"),
        summary_short="Power measures how quickly energy is transferred or used.",
        summary_medium="Electrical power measures the rate at which energy is transferred or converted and is commonly measured in watts.",
        summary_deep=(
            "In circuits, power depends on how quickly electrical energy is being transferred or converted. "
            "A watt is a unit of rate, not resistance, so power and resistance answer different questions about the same circuit."
        ),
        key_points=("Power is measured in watts.", "Power is not the same thing as resistance."),
        common_questions=("What is power?", "What are watts?", "Ohms vs watts"),
        related_topics=("Voltage", "Current", "Resistance", "Ohm's Law"),
        tags=("physics", "electricity", "energy"),
        difficulty_level="general",
        examples=("A 60-watt bulb uses energy faster than a 10-watt bulb.",),
        source_type="curated_local",
        confidence=0.92,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="physics.ohms_law",
        title="Ohm's Law",
        entry_type="formula",
        category="physics",
        subcategory="electricity",
        aliases=("ohms law",),
        summary_short="Ohm's law relates voltage, current, and resistance in many simple circuits.",
        summary_medium="Ohm's law states that voltage equals current times resistance, usually written as V = I R.",
        key_points=("It is a foundational circuit relationship.", "It works best for ohmic materials/components."),
        common_questions=("What is Ohm's law?",),
        related_topics=("Voltage", "Current", "Resistance"),
        tags=("physics", "electricity", "formula"),
        difficulty_level="general",
        examples=("If I = 2 A and R = 5 ohms, then V = 10 volts.",),
        source_type="curated_local",
        confidence=0.95,
        last_updated="2026-03-22",
        formula=KnowledgeFormula(
            formula_text="V = I * R",
            variable_meanings={"V": "voltage", "I": "current", "R": "resistance"},
            units={"V": "volts", "I": "amperes", "R": "ohms"},
            interpretation="Voltage across a component equals the current through it times the resistance.",
            example_usage="If a resistor has R = 5 ohms and current I = 2 A, the voltage is V = 10 V.",
        ),
    ),
    KnowledgeEntry(
        id="physics.newtons_second_law",
        title="Newton's Second Law",
        entry_type="formula",
        category="physics",
        subcategory="mechanics",
        aliases=("newtons 2nd law", "f equals ma", "force equals mass times acceleration"),
        summary_short="Newton's second law relates net force to mass and acceleration.",
        summary_medium="Newton's second law states that the net force on an object equals its mass times its acceleration.",
        tags=("physics", "mechanics", "formula"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.94,
        last_updated="2026-03-22",
        formula=KnowledgeFormula(
            formula_text="F = m * a",
            variable_meanings={"F": "net force", "m": "mass", "a": "acceleration"},
            units={"F": "newtons", "m": "kilograms", "a": "meters per second squared"},
            interpretation="Acceleration increases with force and decreases with mass.",
            example_usage="A 2 kg object accelerating at 3 m/s^2 requires a net force of 6 N.",
        ),
    ),
    KnowledgeEntry(
        id="engineering.control_system",
        title="Control System",
        entry_type="system",
        category="engineering",
        subcategory="control_systems",
        aliases=("control systems",),
        summary_short="A control system manages the behavior of a machine or process toward a target condition.",
        summary_medium=(
            "A control system monitors outputs and adjusts inputs so a system behaves in a desired way. "
            "It can be simple, like a thermostat, or highly complex, like an aircraft flight-control system."
        ),
        key_points=(
            "Control systems often rely on measurement and correction.",
            "Feedback is a core idea in many control systems.",
        ),
        related_topics=("Feedback Loop",),
        tags=("engineering", "systems", "control"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="engineering.electric_motor",
        title="Electric Motor",
        entry_type="system",
        category="engineering",
        subcategory="electromechanical",
        aliases=("motor", "electric motors"),
        summary_short="An electric motor converts electrical energy into mechanical motion.",
        summary_medium=(
            "An electric motor uses electromagnetic forces to turn electrical energy into rotational or linear motion. "
            "It is a core component in many machines, from appliances to vehicles."
        ),
        related_topics=("Voltage", "Current"),
        tags=("engineering", "system", "electromechanical"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="engineering.feedback_loop",
        title="Feedback Loop",
        entry_type="system",
        category="engineering",
        subcategory="control_systems",
        aliases=("feedback loops",),
        summary_short="A feedback loop is a process where a system's output is fed back as input to influence future behavior.",
        summary_medium="In control systems, feedback loops are used to stabilize, regulate, or adapt behavior based on measured output.",
        tags=("engineering", "systems", "control"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.88,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="engineering.propulsion",
        title="Propulsion System",
        entry_type="system",
        category="engineering",
        subcategory="aerospace",
        aliases=("propulsion", "engine propulsion"),
        summary_short="A propulsion system generates thrust to move a vehicle through air, space, or another medium.",
        summary_medium="A propulsion system produces force that pushes a vehicle forward. The exact design depends on the environment, energy source, and performance constraints.",
        tags=("engineering", "aerospace", "system"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.85,
        last_updated="2026-03-22",
    ),
    KnowledgeEntry(
        id="engineering.rocket_engine",
        title="Rocket Engine",
        entry_type="system",
        category="engineering",
        subcategory="aerospace",
        aliases=("rocket engines",),
        summary_short="A rocket engine produces thrust by expelling mass at high speed.",
        summary_medium=(
            "A rocket engine generates thrust by accelerating exhaust in one direction so the vehicle is pushed in the opposite direction. "
            "Unlike air-breathing engines, rockets carry both fuel and oxidizer, which lets them operate in space."
        ),
        key_points=(
            "Rockets do not need outside air to operate.",
            "Thrust depends strongly on exhaust velocity and mass flow rate.",
        ),
        related_topics=("Propulsion System", "Newton's Second Law"),
        tags=("engineering", "aerospace", "propulsion"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-22",
    ),
    # Coverage expansion checklist for new entries:
    # title, aliases, explanation body, discrete related entries, comparison candidates.
    KnowledgeEntry(
        id="astronomy.escape_velocity",
        title="Escape Velocity",
        entry_type="concept",
        category="astronomy",
        subcategory="celestial_mechanics",
        aliases=("escape speed",),
        summary_short="Escape velocity is the speed needed to leave a body's gravity without more propulsion.",
        summary_medium=(
            "Escape velocity is the minimum speed an object needs to move away from a gravitating body without falling back, assuming no further thrust and no drag. "
            "It depends on the body's mass and the distance from its center."
        ),
        related_topics=("Gravity", "Black Hole", "Rocket Engine"),
        tags=("astronomy", "physics", "gravity"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-23",
    ),
    KnowledgeEntry(
        id="astronomy.great_attractor",
        title="Great Attractor",
        entry_type="object",
        category="astronomy",
        subcategory="large_scale_structure",
        aliases=("the great attractor",),
        summary_short="The Great Attractor is a region of strong gravitational influence that affects the motion of many nearby galaxies.",
        summary_medium=(
            "The Great Attractor is an apparent concentration of mass that pulls on galaxies across a large part of the local universe, including the Milky Way's broader neighborhood. "
            "Astronomers infer it from galaxy motions rather than seeing one simple object by itself, because much of the region lies behind the plane of the Milky Way."
        ),
        key_points=(
            "It is not a single ordinary galaxy but a large-scale mass concentration.",
            "Astronomers study it through peculiar velocities, which are galaxy motions beyond simple cosmic expansion.",
        ),
        related_topics=("Hydra-Centaurus Supercluster", "Laniakea Supercluster", "Milky Way"),
        tags=("astronomy", "cosmology", "large_scale_structure"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.91,
        last_updated="2026-04-01",
    ),
    KnowledgeEntry(
        id="astronomy.hydra_centaurus_supercluster",
        title="Hydra-Centaurus Supercluster",
        entry_type="system",
        category="astronomy",
        subcategory="large_scale_structure",
        aliases=("hydra centaurus", "hydra-centaurus", "hydra centaurus supercluster"),
        summary_short="The Hydra-Centaurus Supercluster is a large concentration of galaxies in the nearby universe and is closely associated with the Great Attractor region.",
        summary_medium=(
            "The Hydra-Centaurus Supercluster is a major nearby galaxy concentration that sits in the same broad region of space as the Great Attractor. "
            "It matters because galaxy flows toward that direction helped reveal that a large amount of mass is shaping local cosmic motion."
        ),
        key_points=(
            "It is part of the larger web of galaxy superclusters in the nearby universe.",
            "It is often discussed alongside the Great Attractor because of observed galaxy motions in that direction.",
        ),
        related_topics=("Great Attractor", "Laniakea Supercluster", "Galaxy"),
        tags=("astronomy", "cosmology", "supercluster"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-04-01",
    ),
    KnowledgeEntry(
        id="astronomy.laniakea_supercluster",
        title="Laniakea Supercluster",
        entry_type="system",
        category="astronomy",
        subcategory="large_scale_structure",
        aliases=("laniakea",),
        summary_short="The Laniakea Supercluster is the larger supercluster structure that includes the Milky Way and the region associated with the Great Attractor.",
        summary_medium=(
            "The Laniakea Supercluster is a large mapped region of galaxies whose motions flow toward a common gravitational basin. "
            "It includes the Milky Way and helps place the Great Attractor in a broader large-scale cosmic context."
        ),
        related_topics=("Great Attractor", "Hydra-Centaurus Supercluster", "Milky Way"),
        tags=("astronomy", "cosmology", "supercluster"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.89,
        last_updated="2026-04-01",
    ),
    KnowledgeEntry(
        id="astronomy.andromeda_galaxy",
        title="Andromeda Galaxy",
        entry_type="system",
        category="astronomy",
        subcategory="galaxy",
        aliases=("andromeda", "m31"),
        summary_short="The Andromeda Galaxy is the nearest large spiral galaxy to the Milky Way.",
        summary_medium=(
            "The Andromeda Galaxy is a large spiral galaxy near the Milky Way and is one of the dominant galaxies in the Local Group. "
            "Astronomers study it because it is close enough to resolve in detail and because it is expected to merge with the Milky Way in the distant future."
        ),
        related_topics=("Milky Way", "Galaxy"),
        tags=("astronomy", "galaxy", "local_group"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-04-01",
    ),
    KnowledgeEntry(
        id="astronomy.dark_matter",
        title="Dark Matter",
        entry_type="concept",
        category="astronomy",
        subcategory="cosmology",
        aliases=("dark matter halo",),
        summary_short="Dark matter is the unseen matter astronomers infer from gravity because visible matter alone cannot explain many cosmic motions.",
        summary_medium=(
            "Dark matter is a form of matter inferred from gravitational effects such as galaxy rotation, cluster dynamics, and gravitational lensing. "
            "It does not appear to emit or absorb light in the ordinary way, but it strongly affects the structure and evolution of the universe."
        ),
        related_topics=("Galaxy", "Great Attractor", "Gravity"),
        tags=("astronomy", "cosmology", "gravity"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-04-01",
    ),
    KnowledgeEntry(
        id="astronomy.redshift",
        title="Redshift",
        entry_type="concept",
        category="astronomy",
        subcategory="cosmology",
        aliases=("cosmological redshift",),
        summary_short="Redshift describes light shifting to longer wavelengths, often because an object is moving away or space itself is expanding.",
        summary_medium=(
            "Redshift is the shift of light toward longer wavelengths. "
            "In astronomy it is used to study motion, gravity, and cosmic expansion, making it one of the main tools for measuring how galaxies and the universe behave."
        ),
        related_topics=("Galaxy", "Great Attractor", "Big Bang"),
        tags=("astronomy", "cosmology", "light"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.89,
        last_updated="2026-04-01",
    ),
    KnowledgeEntry(
        id="astronomy.big_bang",
        title="Big Bang",
        entry_type="event",
        category="astronomy",
        subcategory="cosmology",
        aliases=("big bang theory",),
        summary_short="The Big Bang is the standard cosmological model describing the early hot, dense expansion of the universe.",
        summary_medium=(
            "The Big Bang model says the observable universe evolved from an earlier state that was much hotter and denser than it is now. "
            "It does not mean a normal explosion into empty space; it describes the expansion of space and the changing state of the early universe."
        ),
        related_topics=("Redshift", "Dark Matter"),
        tags=("astronomy", "cosmology", "universe"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-04-01",
    ),
    KnowledgeEntry(
        id="astronomy.supernova",
        title="Supernova",
        entry_type="event",
        category="astronomy",
        subcategory="stellar_event",
        aliases=("supernovas", "stellar explosion"),
        summary_short="A supernova is a powerful stellar explosion that can outshine an entire galaxy for a short time.",
        summary_medium=(
            "A supernova is a violent stellar explosion that occurs when certain stars collapse or when a white dwarf becomes unstable. "
            "Supernovae help spread heavy elements through space and can leave behind neutron stars or black holes."
        ),
        related_topics=("Star", "Neutron Star", "Black Hole"),
        tags=("astronomy", "stellar_evolution", "explosion"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.89,
        last_updated="2026-04-01",
    ),
    KnowledgeEntry(
        id="astronomy.white_dwarf",
        title="White Dwarf",
        entry_type="object",
        category="astronomy",
        subcategory="stellar_remnant",
        aliases=("white dwarfs",),
        summary_short="A white dwarf is the hot, dense remnant left after a lower-mass star exhausts its nuclear fuel.",
        summary_medium=(
            "A white dwarf is a compact stellar remnant formed when a Sun-like star sheds its outer layers and leaves behind its dense core. "
            "It no longer produces energy by core fusion, but it can stay hot and slowly cool over very long times."
        ),
        related_topics=("Star", "Supernova"),
        tags=("astronomy", "stellar_remnant"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.88,
        last_updated="2026-04-01",
    ),
    KnowledgeEntry(
        id="astronomy.sagittarius_a_star",
        title="Sagittarius A*",
        entry_type="object",
        category="astronomy",
        subcategory="black_hole",
        aliases=("sgr a*", "sagittarius a star"),
        summary_short="Sagittarius A* is the supermassive black hole at the center of the Milky Way.",
        summary_medium=(
            "Sagittarius A* is the compact radio source associated with the supermassive black hole at the center of the Milky Way. "
            "Astronomers infer its mass from the rapid orbits of nearby stars around an apparently dark central object."
        ),
        related_topics=("Milky Way", "Black Hole"),
        tags=("astronomy", "galactic_center", "black_hole"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.89,
        last_updated="2026-04-01",
    ),
    KnowledgeEntry(
        id="astronomy.hubble_space_telescope",
        title="Hubble Space Telescope",
        entry_type="object",
        category="astronomy",
        subcategory="observatory",
        aliases=("hubble", "hst", "hubble telescope"),
        summary_short="The Hubble Space Telescope is a space observatory that has provided major observations across astronomy since 1990.",
        summary_medium=(
            "The Hubble Space Telescope is an orbiting observatory launched in 1990 that studies the universe in visible, ultraviolet, and near-infrared light. "
            "It is important because being above Earth's atmosphere lets it capture sharper images and sensitive measurements of distant objects."
        ),
        related_topics=("Galaxy", "Milky Way"),
        tags=("astronomy", "observatory", "space_telescope"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.89,
        last_updated="2026-04-01",
    ),
    KnowledgeEntry(
        id="physics.energy",
        title="Energy",
        entry_type="concept",
        category="physics",
        subcategory="fundamental_quantity",
        aliases=("energies",),
        summary_short="Energy is the capacity to do work or cause physical change.",
        summary_medium=(
            "Energy is a conserved physical quantity that can appear in forms like kinetic, potential, thermal, electrical, and chemical energy. "
            "Physics often tracks how energy is transferred or transformed rather than created from nothing."
        ),
        related_topics=("Power", "Work", "Voltage"),
        tags=("physics", "work", "conservation"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.91,
        last_updated="2026-03-23",
    ),
    KnowledgeEntry(
        id="physics.force",
        title="Force",
        entry_type="concept",
        category="physics",
        subcategory="mechanics",
        aliases=("forces",),
        summary_short="A force is an interaction that can change an object's motion.",
        summary_medium=(
            "A force is a push or pull that can accelerate, slow, deform, or redirect an object. "
            "In classical mechanics, net force is tied to acceleration through Newton's second law."
        ),
        related_topics=("Acceleration", "Newton's Second Law"),
        tags=("physics", "mechanics", "motion"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-23",
    ),
    KnowledgeEntry(
        id="physics.momentum",
        title="Momentum",
        entry_type="concept",
        category="physics",
        subcategory="mechanics",
        aliases=("linear momentum",),
        summary_short="Momentum measures how much motion an object has as mass times velocity.",
        summary_medium=(
            "Momentum combines mass and velocity into one quantity that helps describe how hard motion is to stop or redirect. "
            "It is especially useful in collisions because total momentum is conserved in isolated systems."
        ),
        related_topics=("Force", "Acceleration"),
        tags=("physics", "mechanics", "conservation"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.89,
        last_updated="2026-03-23",
    ),
    KnowledgeEntry(
        id="engineering.thrust",
        title="Thrust",
        entry_type="concept",
        category="engineering",
        subcategory="aerospace",
        aliases=("engine thrust",),
        summary_short="Thrust is the forward force produced by a propulsion system.",
        summary_medium=(
            "Thrust is the force that pushes a vehicle by accelerating mass in the opposite direction. "
            "In rockets and jets, thrust depends on exhaust velocity, mass flow, and the surrounding pressure conditions."
        ),
        related_topics=("Rocket Engine", "Propulsion System", "Force"),
        tags=("engineering", "aerospace", "propulsion"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-23",
    ),
    KnowledgeEntry(
        id="engineering.specific_impulse",
        title="Specific Impulse",
        entry_type="concept",
        category="engineering",
        subcategory="aerospace",
        aliases=(),
        summary_short="Specific impulse measures how efficiently a rocket uses propellant.",
        summary_medium=(
            "Specific impulse is a standard rocket-performance metric that describes how much thrust you get per unit weight flow of propellant. "
            "Higher specific impulse generally means a propulsion system uses propellant more efficiently."
        ),
        related_topics=("Rocket Engine", "Thrust", "Propulsion System"),
        tags=("engineering", "aerospace", "propulsion"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.88,
        last_updated="2026-03-23",
    ),
    KnowledgeEntry(
        id="systems.algorithm",
        title="Algorithm",
        entry_type="concept",
        category="systems",
        subcategory="computing",
        aliases=("algorithms",),
        summary_short="An algorithm is a step-by-step procedure for solving a problem or performing a computation.",
        summary_medium=(
            "An algorithm is a defined process for transforming inputs into outputs. "
            "In computing, algorithms are judged by correctness, clarity, efficiency, and how well they scale with input size."
        ),
        related_topics=("Data Structure",),
        tags=("systems", "computing", "logic"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-23",
    ),
    KnowledgeEntry(
        id="systems.data_structure",
        title="Data Structure",
        entry_type="concept",
        category="systems",
        subcategory="computing",
        aliases=("data structures",),
        summary_short="A data structure is an organized way to store and access data.",
        summary_medium=(
            "A data structure defines how data is arranged so operations like lookup, insertion, deletion, or traversal can be done effectively. "
            "Different structures trade off speed, memory use, ordering, and flexibility."
        ),
        related_topics=("Algorithm",),
        tags=("systems", "computing", "storage"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-03-23",
    ),
    KnowledgeEntry(
        id="systems.operating_system",
        title="Operating System",
        entry_type="system",
        category="systems",
        subcategory="computing",
        aliases=("operating systems",),
        summary_short="An operating system manages hardware resources and provides core services for software.",
        summary_medium=(
            "An operating system coordinates memory, processes, files, devices, and scheduling so programs can run on a computer. "
            "It acts as the main layer between hardware and most application software."
        ),
        related_topics=("Control System", "Algorithm"),
        tags=("systems", "computing", "software"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.89,
        last_updated="2026-03-23",
    ),
    KnowledgeEntry(
        id="history.roman_empire",
        title="Roman Empire",
        entry_type="system",
        category="history",
        subcategory="empire",
        aliases=("ancient rome", "the roman empire"),
        summary_short="The Roman Empire was the long-lived imperial state centered on Rome that dominated much of the Mediterranean world.",
        summary_medium=(
            "The Roman Empire was the political system that followed the Roman Republic and eventually ruled large parts of Europe, North Africa, and the Near East. "
            "It matters historically for its law, military power, infrastructure, language influence, and long institutional legacy."
        ),
        related_topics=("Julius Caesar",),
        tags=("history", "rome", "empire"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-04-01",
    ),
    KnowledgeEntry(
        id="history.julius_caesar",
        title="Julius Caesar",
        entry_type="person",
        category="history",
        subcategory="leader",
        aliases=("caesar",),
        summary_short="Julius Caesar was a Roman general and statesman whose rise helped end the Roman Republic.",
        summary_medium=(
            "Julius Caesar was a Roman military and political leader whose conquests, civil war, and concentration of power transformed Roman politics. "
            "His assassination in 44 BCE became a turning point in the collapse of the Roman Republic and the rise of imperial rule."
        ),
        related_topics=("Roman Empire",),
        tags=("history", "rome", "leadership"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-04-01",
    ),
    KnowledgeEntry(
        id="history.french_revolution",
        title="French Revolution",
        entry_type="event",
        category="history",
        subcategory="revolution",
        aliases=("the french revolution",),
        summary_short="The French Revolution was the late-18th-century upheaval that overthrew the French monarchy and reshaped French politics.",
        summary_medium=(
            "The French Revolution began in 1789 as a political and social upheaval that challenged monarchy, privilege, and old-regime institutions in France. "
            "It is historically important because it transformed ideas about citizenship, sovereignty, rights, and modern political change."
        ),
        related_topics=("Napoleon Bonaparte",),
        tags=("history", "revolution", "france"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.89,
        last_updated="2026-04-01",
    ),
    KnowledgeEntry(
        id="history.napoleon_bonaparte",
        title="Napoleon Bonaparte",
        entry_type="person",
        category="history",
        subcategory="leader",
        aliases=("napoleon",),
        summary_short="Napoleon Bonaparte was a French military leader and ruler who rose from the French Revolution and dominated much of Europe for a time.",
        summary_medium=(
            "Napoleon Bonaparte was a French general who rose to power after the French Revolution and later ruled as emperor. "
            "He is remembered for military expansion, legal reforms such as the Napoleonic Code, and the wars that reshaped Europe."
        ),
        related_topics=("French Revolution",),
        tags=("history", "france", "military"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.89,
        last_updated="2026-04-01",
    ),
    KnowledgeEntry(
        id="history.world_war_i",
        title="World War I",
        entry_type="event",
        category="history",
        subcategory="war",
        aliases=("wwi", "first world war", "world war one"),
        summary_short="World War I was a global war from 1914 to 1918 centered largely in Europe.",
        summary_medium=(
            "World War I was a major international conflict fought from 1914 to 1918 among large alliance systems centered in Europe. "
            "It is historically important because of its industrial scale, mass casualties, and the political changes it triggered afterward."
        ),
        related_topics=("World War II",),
        tags=("history", "war", "global"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.89,
        last_updated="2026-04-01",
    ),
    KnowledgeEntry(
        id="history.world_war_ii",
        title="World War II",
        entry_type="event",
        category="history",
        subcategory="war",
        aliases=("wwii", "ww2", "world war 2", "world war ii", "second world war", "world war two"),
        summary_short="World War II was a global war from 1939 to 1945 involving most of the world's major powers.",
        summary_medium=(
            "World War II was a global conflict fought from 1939 to 1945 that involved large alliance blocs across Europe, Africa, Asia, and the Pacific. "
            "It matters historically because of its enormous scale, the Holocaust, the reshaping of global power, and the beginning of the postwar order."
        ),
        related_topics=("World War I", "Cold War"),
        tags=("history", "war", "global"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.9,
        last_updated="2026-04-01",
    ),
    KnowledgeEntry(
        id="history.great_depression",
        title="Great Depression",
        entry_type="event",
        category="history",
        subcategory="economic_crisis",
        aliases=("the great depression",),
        summary_short="The Great Depression was the severe global economic crisis that began in 1929 and lasted through much of the 1930s.",
        summary_medium=(
            "The Great Depression was a worldwide economic collapse marked by unemployment, bank failures, business contraction, and long-lasting social hardship. "
            "It reshaped economic policy and deeply influenced politics around the world."
        ),
        related_topics=("World War II",),
        tags=("history", "economics", "crisis"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.89,
        last_updated="2026-04-01",
    ),
    KnowledgeEntry(
        id="history.cold_war",
        title="Cold War",
        entry_type="event",
        category="history",
        subcategory="geopolitics",
        aliases=("the cold war",),
        summary_short="The Cold War was the long geopolitical rivalry between the United States and the Soviet Union after World War II.",
        summary_medium=(
            "The Cold War was the prolonged political, military, and ideological rivalry between the United States and the Soviet Union and their allies. "
            "Although it did not become a full direct war between the two superpowers, it shaped global alliances, proxy conflicts, arms races, and diplomacy for decades."
        ),
        related_topics=("World War II",),
        tags=("history", "geopolitics", "global"),
        difficulty_level="general",
        source_type="curated_local",
        confidence=0.89,
        last_updated="2026-04-01",
    ),
)


SEED_RELATIONSHIPS: tuple[KnowledgeRelationship, ...] = (
    KnowledgeRelationship("astronomy.galaxy", "related_to", "astronomy.star"),
    KnowledgeRelationship("astronomy.milky_way", "part_of", "astronomy.galaxy"),
    KnowledgeRelationship("astronomy.milky_way", "related_to", "astronomy.black_hole"),
    KnowledgeRelationship("astronomy.star", "related_to", "physics.gravity"),
    KnowledgeRelationship("astronomy.black_hole", "compares_with", "astronomy.neutron_star"),
    KnowledgeRelationship("astronomy.neutron_star", "compares_with", "astronomy.black_hole"),
    KnowledgeRelationship("astronomy.saturn", "part_of", "astronomy.solar_system"),
    KnowledgeRelationship("astronomy.event_horizon", "part_of", "astronomy.black_hole"),
    KnowledgeRelationship("astronomy.orbit", "related_to", "astronomy.solar_system"),
    KnowledgeRelationship("astronomy.escape_velocity", "related_to", "physics.gravity"),
    KnowledgeRelationship("astronomy.escape_velocity", "related_to", "engineering.rocket_engine"),
    KnowledgeRelationship("astronomy.great_attractor", "related_to", "astronomy.hydra_centaurus_supercluster"),
    KnowledgeRelationship("astronomy.great_attractor", "related_to", "astronomy.laniakea_supercluster"),
    KnowledgeRelationship("astronomy.hydra_centaurus_supercluster", "related_to", "astronomy.great_attractor"),
    KnowledgeRelationship("astronomy.laniakea_supercluster", "related_to", "astronomy.great_attractor"),
    KnowledgeRelationship("astronomy.andromeda_galaxy", "related_to", "astronomy.milky_way"),
    KnowledgeRelationship("astronomy.dark_matter", "related_to", "physics.gravity"),
    KnowledgeRelationship("astronomy.redshift", "related_to", "astronomy.big_bang"),
    KnowledgeRelationship("astronomy.supernova", "related_to", "astronomy.neutron_star"),
    KnowledgeRelationship("astronomy.supernova", "related_to", "astronomy.black_hole"),
    KnowledgeRelationship("astronomy.white_dwarf", "related_to", "astronomy.star"),
    KnowledgeRelationship("astronomy.sagittarius_a_star", "part_of", "astronomy.milky_way"),
    KnowledgeRelationship("astronomy.hubble_space_telescope", "related_to", "astronomy.galaxy"),
    KnowledgeRelationship("physics.voltage", "related_to", "physics.current"),
    KnowledgeRelationship("physics.voltage", "related_to", "physics.resistance"),
    KnowledgeRelationship("physics.power", "related_to", "physics.voltage"),
    KnowledgeRelationship("physics.power", "related_to", "physics.current"),
    KnowledgeRelationship("physics.power", "related_to", "physics.resistance"),
    KnowledgeRelationship("physics.energy", "related_to", "physics.power"),
    KnowledgeRelationship("physics.atom", "related_to", "physics.energy"),
    KnowledgeRelationship("physics.force", "related_to", "physics.acceleration"),
    KnowledgeRelationship("physics.momentum", "related_to", "physics.force"),
    KnowledgeRelationship("physics.ohms_law", "related_to", "physics.voltage"),
    KnowledgeRelationship("physics.ohms_law", "related_to", "physics.current"),
    KnowledgeRelationship("physics.newtons_second_law", "related_to", "physics.acceleration"),
    KnowledgeRelationship("history.history", "related_to", "history.american_revolution"),
    KnowledgeRelationship("history.george_washington", "related_to", "history.american_revolution"),
    KnowledgeRelationship("history.abraham_lincoln", "related_to", "history.american_civil_war"),
    KnowledgeRelationship("history.julius_caesar", "related_to", "history.roman_empire"),
    KnowledgeRelationship("history.french_revolution", "related_to", "history.napoleon_bonaparte"),
    KnowledgeRelationship("history.world_war_i", "related_to", "history.world_war_ii"),
    KnowledgeRelationship("history.world_war_ii", "related_to", "history.cold_war"),
    KnowledgeRelationship("history.great_depression", "related_to", "history.world_war_ii"),
    KnowledgeRelationship("math.integral", "related_to", "math.derivative"),
    KnowledgeRelationship("engineering.control_system", "related_to", "engineering.feedback_loop"),
    KnowledgeRelationship("engineering.rocket_engine", "part_of", "engineering.propulsion"),
    KnowledgeRelationship("engineering.rocket_engine", "related_to", "engineering.thrust"),
    KnowledgeRelationship("engineering.rocket_engine", "related_to", "engineering.specific_impulse"),
    KnowledgeRelationship("engineering.thrust", "related_to", "physics.force"),
    KnowledgeRelationship("systems.algorithm", "related_to", "systems.data_structure"),
    KnowledgeRelationship("systems.operating_system", "related_to", "systems.algorithm"),
)


SEED_ENTRIES = SEED_ENTRIES + EXPANSION_ENTRIES
SEED_RELATIONSHIPS = SEED_RELATIONSHIPS + EXPANSION_RELATIONSHIPS
