from __future__ import annotations


SOCIAL_KIND_BY_PHRASE: dict[str, str] = {
    "hello": "conversation.greeting",
    "hello lumen": "conversation.greeting",
    "hey": "conversation.greeting",
    "hey lumen": "conversation.greeting",
    "hey there": "conversation.greeting",
    "hey there lumen": "conversation.greeting",
    "hi": "conversation.greeting",
    "hi lumen": "conversation.greeting",
    "hi there": "conversation.greeting",
    "hi there lumen": "conversation.greeting",
    "good morning": "conversation.greeting",
    "good afternoon": "conversation.greeting",
    "good evening": "conversation.greeting",
    "good morning lumen": "conversation.greeting",
    "good afternoon lumen": "conversation.greeting",
    "good evening lumen": "conversation.greeting",
    "good to see you": "conversation.greeting",
    "good to see you too": "conversation.greeting",
    "good to have you back": "conversation.greeting",
    "nice to see you": "conversation.greeting",
    "nice to see you too": "conversation.greeting",
    "lumen": "conversation.greeting",
    "yo": "conversation.greeting",
    "yo lumen": "conversation.greeting",
    "sup": "conversation.check_in",
    "yo whats up": "conversation.check_in",
    "yo what's up": "conversation.check_in",
    "thanks": "conversation.gratitude",
    "thank you": "conversation.gratitude",
    "thank you so much": "conversation.gratitude",
    "thx": "conversation.gratitude",
    "thx lumen": "conversation.gratitude",
    "ty": "conversation.gratitude",
    "ty lumen": "conversation.gratitude",
    "tysm": "conversation.gratitude",
    "tysm lumen": "conversation.gratitude",
    "lumen thanks": "conversation.gratitude",
    "lumen thank you": "conversation.gratitude",
    "lumen thank you so much": "conversation.gratitude",
    "thanks lumen": "conversation.gratitude",
    "thank you lumen": "conversation.gratitude",
    "thank you so much lumen": "conversation.gratitude",
    "thanks a lot": "conversation.gratitude",
    "thanks a ton": "conversation.gratitude",
    "appreciate it": "conversation.gratitude",
    "appreciate you": "conversation.gratitude",
    "really appreciate it": "conversation.gratitude",
    "really appreciate you": "conversation.gratitude",
    "thanks a lot lumen": "conversation.gratitude",
    "appreciate it lumen": "conversation.gratitude",
    "appreciate you lumen": "conversation.gratitude",
    "yo lumen thanks": "conversation.gratitude",
    "thanks so much": "conversation.gratitude",
    "thanks so much lumen": "conversation.gratitude",
    "great job": "conversation.affirmation",
    "great job lumen": "conversation.affirmation",
    "you are awesome": "conversation.affirmation",
    "you're awesome": "conversation.affirmation",
    "youre awesome": "conversation.affirmation",
    "you are great": "conversation.affirmation",
    "you're great": "conversation.affirmation",
    "good work": "conversation.affirmation",
    "good job": "conversation.affirmation",
    "nice job": "conversation.affirmation",
    "nice one": "conversation.affirmation",
    "great work": "conversation.affirmation",
    "well done": "conversation.affirmation",
    "how are you": "conversation.check_in",
    "how are you doing": "conversation.check_in",
    "how's it going": "conversation.check_in",
    "hows it going": "conversation.check_in",
    "what is up": "conversation.check_in",
    "what's up": "conversation.check_in",
    "whats up": "conversation.check_in",
    "how r u": "conversation.check_in",
    "how are ya": "conversation.check_in",
    "how you doing": "conversation.check_in",
    "how you doin": "conversation.check_in",
    "you good": "conversation.check_in",
    "how have you been": "conversation.check_in",
    "how've you been": "conversation.check_in",
    "lol": "conversation.micro_turn",
    "haha": "conversation.micro_turn",
    "lmao": "conversation.micro_turn",
    "hehe": "conversation.micro_turn",
    "yeah": "conversation.micro_turn",
    "yep": "conversation.micro_turn",
    "yup": "conversation.micro_turn",
    "true": "conversation.micro_turn",
    "right": "conversation.micro_turn",
    "sure": "conversation.micro_turn",
    "okay yeah": "conversation.micro_turn",
    "got it": "conversation.micro_turn",
    "fair": "conversation.micro_turn",
    "hmm": "conversation.micro_turn",
    "idk": "conversation.micro_turn",
    "nah": "conversation.micro_turn",
    "sounds good": "conversation.acknowledgment",
    "that sounds good": "conversation.acknowledgment",
    "that makes sense": "conversation.acknowledgment",
    "makes sense": "conversation.acknowledgment",
    "gotcha": "conversation.acknowledgment",
    "understood": "conversation.acknowledgment",
    "i get it": "conversation.acknowledgment",
    "nice": "conversation.acknowledgment",
    "nice work": "conversation.acknowledgment",
    "perfect": "conversation.acknowledgment",
    "great": "conversation.acknowledgment",
    "okay": "conversation.acknowledgment",
    "ok": "conversation.acknowledgment",
    "alright": "conversation.acknowledgment",
    "all right": "conversation.acknowledgment",
    "lets do it": "conversation.transition",
    "let's do it": "conversation.transition",
    "go ahead": "conversation.transition",
    "proceed": "conversation.transition",
    "lets continue": "conversation.transition",
    "let's continue": "conversation.transition",
    "ready": "conversation.transition",
    "ready?": "conversation.transition",
    "can we start": "conversation.transition",
    "can we start?": "conversation.transition",
    "lets go": "conversation.transition",
    "let's go": "conversation.transition",
    "lets move": "conversation.transition",
    "let's move": "conversation.transition",
    "lets begin": "conversation.transition",
    "let's begin": "conversation.transition",
    "bye": "conversation.farewell",
    "goodbye": "conversation.farewell",
    "bye lumen": "conversation.farewell",
    "goodbye lumen": "conversation.farewell",
    "see you": "conversation.farewell",
    "see you later": "conversation.farewell",
    "see you later lumen": "conversation.farewell",
    "later": "conversation.farewell",
    "later lumen": "conversation.farewell",
    "talk later": "conversation.farewell",
    "talk later lumen": "conversation.farewell",
    "catch you later": "conversation.farewell",
    "catch you later lumen": "conversation.farewell",
    "see ya": "conversation.farewell",
    "see ya lumen": "conversation.farewell",
    "talk soon": "conversation.farewell",
    "see ya later": "conversation.farewell",
    "take care": "conversation.farewell",
    "have a good one": "conversation.farewell",
    "until next time": "conversation.farewell",
    "brb": "conversation.farewell",
    "good night": "conversation.farewell",
    "goodnight": "conversation.farewell",
    "good night lumen": "conversation.farewell",
    "goodnight lumen": "conversation.farewell",
}


def phrases_for(kind: str) -> tuple[str, ...]:
    return tuple(
        phrase
        for phrase, phrase_kind in SOCIAL_KIND_BY_PHRASE.items()
        if phrase_kind == kind
    )
